<section class="sp-top-bottom100 bg-white">
	<div class="container text-center">
		<div class="styled-heading">
			<h3>PROMOTIONAL PRODUCTS FREE SHIPPING</h3>
		</div>
		<div class="styled-heading-top">
			<span>Our Happy Clients</span>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12 brands_img">
			<a onclick="window.open('pub/media/brands/microsoft_proof.jpg','name','width=400,height=400')" href="pub/media/brands/microsoft_proof.jpg" target="popup"><img alt="" src="pub/media/brands/client-1.jpg" /></a>
			<a onclick="window.open('pub/media/brands/ucla_proof.jpg','name','width=400,height=400')" href="pub/media/brands/ucla_proof.jpg" target="popup"><img alt="" src="pub/media/brands/client-2.jpg" /></a>
			<a onclick="window.open('pub/media/brands/google_proof.jpg','name','width=400,height=400')" href="pub/media/brands/google_proof.jpg" target="popup"><img alt="" src="pub/media/brands/client-3.jpg" /></a>
			<a onclick="window.open('pub/media/brands/homedepot_proof.jpg','name','width=400,height=400')" href="pub/media/brands/homedepot_proof.jpg" target="popup"><img alt="" src="pub/media/brands/client-4.jpg" /></a>
			<a onclick="window.open('pub/media/brands/hyatt_proof.jpg','name','width=400,height=400')" href="pub/media/brands/hyatt_proof.jpg" target="popup"><img alt="" src="pub/media/brands/client-5.jpg" /></a>
			<a onclick="window.open('pub/media/brands/verizon_proof.jpg','name','width=400,height=400')" href="pub/media/brands/verizon_proof.jpg" target="popup"><img alt="" src="pub/media/brands/client-6.jpg" /></a>
			<a onclick="window.open('pub/media/brands/sothebys_proof.jpg','name','width=400,height=400')" href="pub/media/brands/sothebys_proof.jpg" target="popup"><img alt="" src="pub/media/brands/client-7.jpg" /></a>
		</div>
	</div>
</section>